# Generated by Django 3.2.10 on 2021-12-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calenderapp', '0002_auto_20211222_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarattendee',
            name='calender_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calender_attendee', to='calenderapp.calender'),
        ),
        migrations.AlterField(
            model_name='calendarattendee',
            name='event_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendee', to='calenderapp.calendarevent'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_start_date',
            field=models.DateTimeField(),
        ),
    ]
