# Generated by Django 3.2.10 on 2022-01-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('calendar_name', models.CharField(max_length=250)),
                ('access_role', models.CharField(blank=True, max_length=50, null=True)),
                ('select_flg', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_event_key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('event_id', models.CharField(blank=True, max_length=250, null=True)),
                ('event_name', models.CharField(max_length=263)),
                ('event_name_prev', models.CharField(blank=True, max_length=250, null=True)),
                ('event_description', models.TextField()),
                ('event_start_dt', models.DateTimeField()),
                ('event_end_dt', models.DateTimeField()),
                ('event_location', models.TextField()),
                ('delete_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('new_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('location_missing_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('inperson_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('travel_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('zoom_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('msteams_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('gmeet_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('lunch_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('dinner_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('oneonone_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('all_day_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('event_link', models.URLField(blank=True, null=True)),
                ('event_call_link', models.URLField(blank=True, null=True)),
                ('num_attendees', models.IntegerField(blank=True, null=True)),
                ('organizer_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('creator_flg', models.IntegerField(blank=True, default=0, null=True)),
                ('calendar_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calender_event', to='calenderapp.calendarlist')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarAttendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_attendee', models.CharField(blank=True, max_length=200, null=True)),
                ('event_attendee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('response_status', models.CharField(blank=True, max_length=50, null=True)),
                ('self_flg', models.IntegerField(blank=True, null=True)),
                ('calendar_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calender_attendee', to='calenderapp.calendarlist')),
                ('event_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendee', to='calenderapp.calendarevents', to_field='user_event_key')),
            ],
        ),
    ]
