# Generated by Django 3.2.10 on 2022-02-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenderapp', '0002_auto_20220203_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevents',
            name='allDay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
